"""Provider-neutral capability-gap observation plane."""

from .contracts import (
    CapabilityGapAggregate,
    CapabilityGapCollisionError,
    CapabilityGapCorruptionError,
    CapabilityGapDimensions,
    CapabilityGapObservation,
    CapabilityGapUnavailableError,
    CapabilityGapValidationError,
    CapabilityGapWriteContext,
    GapCategory,
    GapDisposition,
    GapKeyV1,
    ImpactKind,
    RequestedOperationKind,
    SafeTargetKind,
    TrustedLimitationCode,
    TrustedLimitationReceipt,
    VerificationKind,
    proposal_for,
    report_id_for,
)
from .host_tool import (
    CapabilityGapHostContext,
    CapabilityGapHostTool,
    CapabilityGapHostToolError,
    CapabilityGapHostToolManifest,
    CapabilityGapProposal,
    CapabilityGapReportResult,
    WorkaroundSuggestionKind,
)
from .service import CapabilityGapService
from .source_tracer import (
    SourceFormatDisposition,
    SourceFormatTrace,
    UnsupportedSourceEvidence,
    trace_unsupported_source_format,
)
from .view import CapabilityGapCompactView, CapabilityGapDetailView
from .workarounds import (
    WorkaroundApprovalPolicy,
    WorkaroundEffect,
    WorkaroundExecutionReceipt,
    WorkaroundInputKind,
    WorkaroundManifest,
    WorkaroundOutputKind,
    WorkaroundReceiptStatus,
    WorkaroundRegistry,
    WorkaroundTask,
)

__all__ = [
    "CapabilityGapAggregate",
    "CapabilityGapCollisionError",
    "CapabilityGapCompactView",
    "CapabilityGapCorruptionError",
    "CapabilityGapDetailView",
    "CapabilityGapDimensions",
    "CapabilityGapHostContext",
    "CapabilityGapHostTool",
    "CapabilityGapHostToolError",
    "CapabilityGapHostToolManifest",
    "CapabilityGapObservation",
    "CapabilityGapProposal",
    "CapabilityGapReportResult",
    "CapabilityGapService",
    "CapabilityGapUnavailableError",
    "CapabilityGapValidationError",
    "CapabilityGapWriteContext",
    "GapCategory",
    "GapDisposition",
    "GapKeyV1",
    "ImpactKind",
    "RequestedOperationKind",
    "SafeTargetKind",
    "SourceFormatDisposition",
    "SourceFormatTrace",
    "TrustedLimitationCode",
    "TrustedLimitationReceipt",
    "UnsupportedSourceEvidence",
    "VerificationKind",
    "WorkaroundApprovalPolicy",
    "WorkaroundEffect",
    "WorkaroundExecutionReceipt",
    "WorkaroundInputKind",
    "WorkaroundManifest",
    "WorkaroundOutputKind",
    "WorkaroundReceiptStatus",
    "WorkaroundRegistry",
    "WorkaroundSuggestionKind",
    "WorkaroundTask",
    "proposal_for",
    "report_id_for",
    "trace_unsupported_source_format",
]
