"""Provider-neutral capability-gap observation plane."""

from .contracts import (
    CapabilityGapAggregate,
    CapabilityGapCollisionError,
    CapabilityGapCorruptionError,
    CapabilityGapDimensions,
    CapabilityGapObservation,
    CapabilityGapUnavailableError,
    CapabilityGapValidationError,
    CapabilityGapWriteContext,
    GapCategory,
    GapDisposition,
    GapKeyV1,
    ImpactKind,
    RequestedOperationKind,
    SafeTargetKind,
    TrustedLimitationCode,
    TrustedLimitationReceipt,
    VerificationKind,
    proposal_for,
    report_id_for,
)
from .host_tool import (
    CapabilityGapHostContext,
    CapabilityGapHostTool,
    CapabilityGapHostToolError,
    CapabilityGapHostToolManifest,
    CapabilityGapProposal,
    CapabilityGapReportResult,
    WorkaroundSuggestionKind,
)
from .service import CapabilityGapService
from .view import CapabilityGapCompactView, CapabilityGapDetailView

__all__ = [
    "CapabilityGapAggregate",
    "CapabilityGapCollisionError",
    "CapabilityGapCompactView",
    "CapabilityGapCorruptionError",
    "CapabilityGapDetailView",
    "CapabilityGapDimensions",
    "CapabilityGapHostContext",
    "CapabilityGapHostTool",
    "CapabilityGapHostToolError",
    "CapabilityGapHostToolManifest",
    "CapabilityGapObservation",
    "CapabilityGapProposal",
    "CapabilityGapReportResult",
    "CapabilityGapService",
    "CapabilityGapUnavailableError",
    "CapabilityGapValidationError",
    "CapabilityGapWriteContext",
    "GapCategory",
    "GapDisposition",
    "GapKeyV1",
    "ImpactKind",
    "RequestedOperationKind",
    "SafeTargetKind",
    "TrustedLimitationCode",
    "TrustedLimitationReceipt",
    "VerificationKind",
    "WorkaroundSuggestionKind",
    "proposal_for",
    "report_id_for",
]
