"""Provider-neutral study-artifact contracts."""

from .content import (
    AnswerBlock,
    ArtifactContent,
    AssessmentItemContent,
    EvidenceObservation,
    ExamBlueprintContent,
    FlashcardContent,
    HybridFlashcardContent,
    MorphologyFlashcardContent,
    StudyArtifactEnvelope,
    StudyBriefContent,
    StudyBriefSection,
)
from .contracts import (
    ArtifactBatchRecord,
    ArtifactDecisionRecord,
    ArtifactProposal,
    ArtifactProposalOrigin,
    ArtifactRevisionRecord,
    ArtifactSnapshot,
    GeneratedBatchProofReceipt,
    ServiceDecisionPolicyReceipt,
    ServiceDecisionPolicyRequest,
    VerifiedGeneratedArtifactBatch,
)
from .events import (
    ARTIFACT_EVENT_TYPES,
    ARTIFACT_SCHEMA_VERSION,
    DECISION_RECORDED,
    PROPOSAL_BATCH_RECORDED,
    decode_decision_recorded,
    decode_proposal_batch_recorded,
)
from .generated_owner import (
    ExamGeneratedBatchOwnerReceipt,
    GeneratedBatchOwnerConflictError,
    GeneratedBatchOwnerKind,
    GeneratedBatchOwnerReceipt,
    GeneratedBatchOwnerRegistry,
    LessonGeneratedBatchOwnerReceipt,
    generated_batch_owner_from_bytes,
)
from .identity import (
    ArtifactProvenance,
    ArtifactProvenanceOrigin,
    GeneratedArtifactProvenance,
    HumanAuthoredArtifactProvenance,
    artifact_batch_id_for,
    artifact_id_for,
    artifact_provenance_from_bytes,
    artifact_provenance_from_json,
    artifact_provenance_to_bytes,
    artifact_provenance_to_json,
    artifact_revision_id_for,
    human_authored_artifact_batch_id_for,
)
from .projection import register_artifact_events
from .service import (
    ArtifactCommandError,
    ArtifactConflictError,
    ArtifactService,
    RetryableArtifactConflictError,
    service_decision_result_fingerprint,
)
from .view import ProjectionArtifactView

__all__ = [
    "ARTIFACT_EVENT_TYPES",
    "ARTIFACT_SCHEMA_VERSION",
    "DECISION_RECORDED",
    "PROPOSAL_BATCH_RECORDED",
    "AnswerBlock",
    "ArtifactBatchRecord",
    "ArtifactCommandError",
    "ArtifactConflictError",
    "ArtifactContent",
    "ArtifactDecisionRecord",
    "ArtifactProposal",
    "ArtifactProposalOrigin",
    "ArtifactProvenance",
    "ArtifactProvenanceOrigin",
    "ArtifactRevisionRecord",
    "ArtifactService",
    "ArtifactSnapshot",
    "AssessmentItemContent",
    "EvidenceObservation",
    "ExamBlueprintContent",
    "ExamGeneratedBatchOwnerReceipt",
    "FlashcardContent",
    "GeneratedArtifactProvenance",
    "GeneratedBatchOwnerConflictError",
    "GeneratedBatchOwnerKind",
    "GeneratedBatchOwnerReceipt",
    "GeneratedBatchOwnerRegistry",
    "GeneratedBatchProofReceipt",
    "HumanAuthoredArtifactProvenance",
    "HybridFlashcardContent",
    "LessonGeneratedBatchOwnerReceipt",
    "MorphologyFlashcardContent",
    "ProjectionArtifactView",
    "RetryableArtifactConflictError",
    "ServiceDecisionPolicyReceipt",
    "ServiceDecisionPolicyRequest",
    "StudyArtifactEnvelope",
    "StudyBriefContent",
    "StudyBriefSection",
    "VerifiedGeneratedArtifactBatch",
    "artifact_batch_id_for",
    "artifact_id_for",
    "artifact_provenance_from_bytes",
    "artifact_provenance_from_json",
    "artifact_provenance_to_bytes",
    "artifact_provenance_to_json",
    "artifact_revision_id_for",
    "decode_decision_recorded",
    "decode_proposal_batch_recorded",
    "generated_batch_owner_from_bytes",
    "human_authored_artifact_batch_id_for",
    "register_artifact_events",
    "service_decision_result_fingerprint",
]
