"""Provider-neutral contracts for bounded external tutor hosts."""

from .context import CapabilityDiscoveryPort, TutorHostContextAssembler
from .contracts import (
    HOST_CONTEXT_SCHEMA_VERSION,
    AdvertisedCapability,
    AnswerDialogueDecision,
    AskLearnerDecision,
    AssistantMessageDecision,
    HostActionIdentity,
    HostFileDescriptor,
    HostRetryReceipt,
    PendingContinuationDescriptor,
    StartCapabilityDecision,
    StopDecision,
    TutorDecision,
    TutorDecisionKind,
    TutorHostContext,
    TutorStopReason,
    decision_fingerprint,
    decision_from_bytes,
    decision_schema,
    decision_to_bytes,
    decision_to_json,
    validate_decision,
)
from .files import (
    HostFileError,
    HostFileReference,
    HostFileRegistry,
    HostFileSnapshot,
    TrustedHostFileIngestionCommand,
    UntrustedHostFileContent,
)
from .runner import (
    RetryableTutorDecisionError,
    ScriptedDecision,
    ScriptedDecisionError,
    ScriptedTutorDecisionPort,
    TutorContinuationRecord,
    TutorHostLimits,
    TutorHostRunner,
    TutorHostRunResult,
    TutorHostRunStatus,
)

__all__ = [
    "HOST_CONTEXT_SCHEMA_VERSION",
    "AdvertisedCapability",
    "AnswerDialogueDecision",
    "AskLearnerDecision",
    "AssistantMessageDecision",
    "CapabilityDiscoveryPort",
    "HostActionIdentity",
    "HostFileDescriptor",
    "HostFileError",
    "HostFileReference",
    "HostFileRegistry",
    "HostFileSnapshot",
    "HostRetryReceipt",
    "PendingContinuationDescriptor",
    "RetryableTutorDecisionError",
    "ScriptedDecision",
    "ScriptedDecisionError",
    "ScriptedTutorDecisionPort",
    "StartCapabilityDecision",
    "StopDecision",
    "TrustedHostFileIngestionCommand",
    "TutorContinuationRecord",
    "TutorDecision",
    "TutorDecisionKind",
    "TutorHostContext",
    "TutorHostContextAssembler",
    "TutorHostLimits",
    "TutorHostRunResult",
    "TutorHostRunStatus",
    "TutorHostRunner",
    "TutorStopReason",
    "UntrustedHostFileContent",
    "decision_fingerprint",
    "decision_from_bytes",
    "decision_schema",
    "decision_to_bytes",
    "decision_to_json",
    "validate_decision",
]
