"""Provider-neutral contracts for bounded external tutor hosts."""

from .context import CapabilityDiscoveryPort, TutorHostContextAssembler
from .contracts import (
    HOST_CONTEXT_SCHEMA_VERSION,
    AdvertisedCapability,
    AnswerDialogueDecision,
    AskLearnerDecision,
    AssistantMessageDecision,
    HostActionIdentity,
    HostFileDescriptor,
    HostRetryReceipt,
    PendingContinuationDescriptor,
    StartCapabilityDecision,
    StopDecision,
    TutorDecision,
    TutorDecisionKind,
    TutorHostContext,
    TutorStopReason,
    decision_fingerprint,
    decision_from_bytes,
    decision_to_bytes,
    decision_to_json,
    validate_decision,
)

__all__ = [
    "HOST_CONTEXT_SCHEMA_VERSION",
    "AdvertisedCapability",
    "AnswerDialogueDecision",
    "AskLearnerDecision",
    "AssistantMessageDecision",
    "CapabilityDiscoveryPort",
    "HostActionIdentity",
    "HostFileDescriptor",
    "HostRetryReceipt",
    "PendingContinuationDescriptor",
    "StartCapabilityDecision",
    "StopDecision",
    "TutorDecision",
    "TutorDecisionKind",
    "TutorHostContext",
    "TutorHostContextAssembler",
    "TutorStopReason",
    "decision_fingerprint",
    "decision_from_bytes",
    "decision_to_bytes",
    "decision_to_json",
    "validate_decision",
]
