"""Deterministic local-source ingestion state contracts."""

from .chunking import CHUNKER_VERSION, ChunkingConfig, chunk_text
from .events import (
    SOURCE_REVISION_INGESTED,
    SOURCE_REVISION_SCHEMA_VERSION,
    SOURCE_REVISION_SELECTED,
    SOURCE_REVISION_SELECTED_SCHEMA_VERSION,
    BlobLoader,
    PersistedChunkingConfig,
    SourceRevisionIngested,
    SourceRevisionSelected,
    decode_source_revision_event,
    decode_source_revision_ingested,
    decode_source_revision_selected,
    decode_source_revision_selected_event,
    source_revision_selected_payload,
)
from .identity import (
    CHUNK_MAX_CHARACTERS,
    CHUNKER_POLICY_VERSION,
    NORMALIZATION_POLICY_VERSION,
    chunk_id_for,
    revision_id_for,
    source_event_id_for,
    source_kind_contract,
    source_revision_selected_event_id_for,
)
from .normalization import (
    NORMALIZATION_VERSION,
    InvalidUtf8Error,
    NormalizedText,
    normalize_utf8,
)
from .projection import (
    chunk_manifest,
    reduce_source_revision,
    reduce_source_revision_selected,
    register_source_revision_events,
    source_manifest,
    source_revision_payload,
)
from .service import (
    IngestionErrorCode,
    IngestionStatus,
    TextIngestionError,
    TextIngestionResult,
    TextIngestionService,
)

__all__ = [
    "CHUNKER_POLICY_VERSION",
    "CHUNKER_VERSION",
    "CHUNK_MAX_CHARACTERS",
    "NORMALIZATION_POLICY_VERSION",
    "NORMALIZATION_VERSION",
    "SOURCE_REVISION_INGESTED",
    "SOURCE_REVISION_SCHEMA_VERSION",
    "SOURCE_REVISION_SELECTED",
    "SOURCE_REVISION_SELECTED_SCHEMA_VERSION",
    "BlobLoader",
    "ChunkingConfig",
    "IngestionErrorCode",
    "IngestionStatus",
    "InvalidUtf8Error",
    "NormalizedText",
    "PersistedChunkingConfig",
    "SourceRevisionIngested",
    "SourceRevisionSelected",
    "TextIngestionError",
    "TextIngestionResult",
    "TextIngestionService",
    "chunk_id_for",
    "chunk_manifest",
    "chunk_text",
    "decode_source_revision_event",
    "decode_source_revision_ingested",
    "decode_source_revision_selected",
    "decode_source_revision_selected_event",
    "normalize_utf8",
    "reduce_source_revision",
    "reduce_source_revision_selected",
    "register_source_revision_events",
    "revision_id_for",
    "source_event_id_for",
    "source_kind_contract",
    "source_manifest",
    "source_revision_payload",
    "source_revision_selected_event_id_for",
    "source_revision_selected_payload",
]
