"""Framework-free, immutable study-domain contracts."""

from .context import ExecutionContext
from .course import CourseProfile, SourcePolicy, TerminologyEntry, TerminologyPolicy
from .errors import ErrorCode, StudyError
from .events import Actor, DomainEvent, PrincipalKind
from .grounding import AnswerSegment, AnswerStatus, GroundedAnswer, SegmentKind
from .identifiers import (
    AnswerId,
    BlobId,
    ChunkId,
    CorrelationId,
    CourseId,
    EventId,
    InteractionId,
    ModelRunId,
    RevisionId,
    RunId,
    SessionId,
    SourceId,
    answer_id_for,
    assistant_interaction_id_for,
    question_interaction_id_for,
    session_event_id_for,
)
from .provenance import (
    AnswerProvenance,
    ClaimOrigin,
    ContentOrigin,
    ModelProvenance,
    ModelUsageProvenance,
    PromptProvenance,
    RetrievalProvenance,
    SourceCommitment,
    StructureOrigin,
    ValidatorProvenance,
    VersionPins,
)
from .session import (
    AnswerRecord,
    ContinuationSummaryV1,
    InteractionKind,
    InteractionRecord,
    SessionStatus,
    StudySession,
    StudySessionRecord,
    SummaryExchange,
)
from .source import BlobRef, Citation, ResolvedCitation, SourceChunk, SourceDocument, SourceKind

__all__ = [
    "Actor",
    "AnswerId",
    "AnswerProvenance",
    "AnswerRecord",
    "AnswerSegment",
    "AnswerStatus",
    "BlobId",
    "BlobRef",
    "ChunkId",
    "Citation",
    "ClaimOrigin",
    "ContentOrigin",
    "ContinuationSummaryV1",
    "CorrelationId",
    "CourseId",
    "CourseProfile",
    "DomainEvent",
    "ErrorCode",
    "EventId",
    "ExecutionContext",
    "GroundedAnswer",
    "InteractionId",
    "InteractionKind",
    "InteractionRecord",
    "ModelProvenance",
    "ModelRunId",
    "ModelUsageProvenance",
    "PrincipalKind",
    "PromptProvenance",
    "ResolvedCitation",
    "RetrievalProvenance",
    "RevisionId",
    "RunId",
    "SegmentKind",
    "SessionId",
    "SessionStatus",
    "SourceChunk",
    "SourceCommitment",
    "SourceDocument",
    "SourceId",
    "SourceKind",
    "SourcePolicy",
    "StructureOrigin",
    "StudyError",
    "StudySession",
    "StudySessionRecord",
    "SummaryExchange",
    "TerminologyEntry",
    "TerminologyPolicy",
    "ValidatorProvenance",
    "VersionPins",
    "answer_id_for",
    "assistant_interaction_id_for",
    "question_interaction_id_for",
    "session_event_id_for",
]
